[templates.dmskitty]
input_path = 'SHELL_DIR/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/dank-theme.conf'

[templates.dmskittytabs]
input_path = 'SHELL_DIR/matugen/templates/kitty-tabs.conf'
output_path = '~/.config/kitty/dank-tabs.conf'