[templates.dmsvscodedefault]
input_path = 'SHELL_DIR/matugen/templates/vscode-color-theme.json'
output_path = '~/.vscode/extensions/local.dynamic-base16-dankshell-0.0.1/themes/dankshell-default-base.json'

[templates.dmsvscodedark]
input_path = 'SHELL_DIR/matugen/templates/vscode-color-theme.json'
output_path = '~/.vscode/extensions/local.dynamic-base16-dankshell-0.0.1/themes/dankshell-dark-base.json'
mode = 'Dark'

[templates.dmsvscodelight]
input_path = 'SHELL_DIR/matugen/templates/vscode-color-theme.json'
output_path = '~/.vscode/extensions/local.dynamic-base16-dankshell-0.0.1/themes/dankshell-light-base.json'
mode = 'Light'
