[colors.primary]
background = '{{colors.background.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

[colors.selection]
text = '{{colors.on_surface.default.hex}}'
background = '{{colors.primary_container.default.hex}}'

[colors.cursor]
text = '{{colors.background.default.hex}}'
cursor = '{{colors.primary.default.hex}}'
